
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robert
 */
public class POS extends javax.swing.JFrame {

    /**
     */
    public POS() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jtxtNumerar = new javax.swing.JTextField();
        jtxtMetoda_plata = new javax.swing.JComboBox<>();
        jtxtRest = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jbtnAnulare_bon = new javax.swing.JButton();
        jbtnIncaseaza = new javax.swing.JButton();
        jButton_Inchidere = new javax.swing.JButton();
        jbtnEmite_bon = new javax.swing.JButton();
        jbtnStergere_produs = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jtxtTVA = new javax.swing.JTextField();
        jtxtPret_Total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtPret_brut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtnDot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtnSprite = new javax.swing.JButton();
        jbtnCola = new javax.swing.JButton();
        jbtnCafea = new javax.swing.JButton();
        jbtnSendvis = new javax.swing.JButton();
        jbtnFanta = new javax.swing.JButton();
        jbtnAripioarePui = new javax.swing.JButton();
        jbtnShaorma = new javax.swing.JButton();
        jbtnHotdog = new javax.swing.JButton();
        jbtnCartofiPai = new javax.swing.JButton();
        jbtnHamburgerSimplu = new javax.swing.JButton();
        jbtnFelie_pizza = new javax.swing.JButton();
        jbtnHamburgerDublu = new javax.swing.JButton();
        jbtnMeniu1 = new javax.swing.JButton();
        jbtnMeniu2 = new javax.swing.JButton();
        jbtnPizzaMare = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem POS Fast Food");
        setBackground(new java.awt.Color(240, 240, 255));
        setForeground(java.awt.Color.black);
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setToolTipText("a");
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plată și finalizare", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metoda de plată", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNumerar.setBackground(new java.awt.Color(238, 238, 238));
        jtxtNumerar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtxtNumerar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtNumerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumerarActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtNumerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 200, 40));

        jtxtMetoda_plata.setBackground(new java.awt.Color(255, 255, 255));
        jtxtMetoda_plata.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtxtMetoda_plata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numerar", "Card bancar", "Card de masă", "Transfer bancar", "Mobile payment" }));
        jtxtMetoda_plata.setBorder(null);
        jtxtMetoda_plata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMetoda_plataActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtMetoda_plata, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 200, 40));

        jtxtRest.setEditable(false);
        jtxtRest.setBackground(new java.awt.Color(238, 238, 238));
        jtxtRest.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtRest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jtxtRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Rest:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 132, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Tip plată:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Sumă primită:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 440, 180));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acțiuni", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAnulare_bon.setBackground(new java.awt.Color(204, 204, 204));
        jbtnAnulare_bon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAnulare_bon.setText("Anulare bon");
        jbtnAnulare_bon.setBorder(null);
        jbtnAnulare_bon.setFocusPainted(false);
        jbtnAnulare_bon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnulare_bonActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnAnulare_bon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, 40));

        jbtnIncaseaza.setBackground(new java.awt.Color(0, 204, 102));
        jbtnIncaseaza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnIncaseaza.setForeground(new java.awt.Color(0, 0, 0));
        jbtnIncaseaza.setText("Încasează");
        jbtnIncaseaza.setBorder(null);
        jbtnIncaseaza.setFocusPainted(false);
        jbtnIncaseaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIncaseazaActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnIncaseaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 40));

        jButton_Inchidere.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Inchidere.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Inchidere.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Inchidere.setText("Închidere aplicație");
        jButton_Inchidere.setBorder(null);
        jButton_Inchidere.setFocusPainted(false);
        jButton_Inchidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InchidereActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Inchidere, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 40));

        jbtnEmite_bon.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEmite_bon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEmite_bon.setText("Emite bon");
        jbtnEmite_bon.setBorder(null);
        jbtnEmite_bon.setFocusPainted(false);
        jbtnEmite_bon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmite_bonActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnEmite_bon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 40));

        jbtnStergere_produs.setBackground(new java.awt.Color(204, 204, 204));
        jbtnStergere_produs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnStergere_produs.setText("Ștergere produs");
        jbtnStergere_produs.setToolTipText("");
        jbtnStergere_produs.setBorder(null);
        jbtnStergere_produs.setFocusPainted(false);
        jbtnStergere_produs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStergere_produsActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnStergere_produs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 380, 180));

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sumar comandă", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTVA.setEditable(false);
        jtxtTVA.setBackground(new java.awt.Color(238, 238, 238));
        jtxtTVA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtxtTVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtTVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTVAActionPerformed(evt);
            }
        });
        jPanel9.add(jtxtTVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 40));

        jtxtPret_Total.setEditable(false);
        jtxtPret_Total.setBackground(new java.awt.Color(238, 238, 238));
        jtxtPret_Total.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jtxtPret_Total.setForeground(new java.awt.Color(0, 0, 0));
        jtxtPret_Total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPret_Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.add(jtxtPret_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("TOTAL DE PLATĂ:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Preț fără TVA:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Valoare TVA:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jtxtPret_brut.setEditable(false);
        jtxtPret_brut.setBackground(new java.awt.Color(238, 238, 238));
        jtxtPret_brut.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtxtPret_brut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtPret_brut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jtxtPret_brut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPret_brutActionPerformed(evt);
            }
        });
        jPanel9.add(jtxtPret_brut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 200, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 420, 180));

        jPanel13.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1340, 230));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tastatura numerică", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnDot.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setBorder(null);
        jbtnDot.setFocusPainted(false);
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 90));

        jbtn0.setBackground(new java.awt.Color(204, 255, 204));
        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setBorder(null);
        jbtn0.setFocusPainted(false);
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 80, 90));

        jbtnC.setBackground(new java.awt.Color(255, 51, 51));
        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnC.setForeground(new java.awt.Color(255, 255, 255));
        jbtnC.setText("C");
        jbtnC.setToolTipText("Șterge");
        jbtnC.setBorder(null);
        jbtnC.setFocusPainted(false);
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 80, 90));

        jbtn3.setBackground(new java.awt.Color(204, 255, 204));
        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setBorder(null);
        jbtn3.setFocusPainted(false);
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, 90));

        jbtn2.setBackground(new java.awt.Color(204, 255, 204));
        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setBorder(null);
        jbtn2.setFocusPainted(false);
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 80, 90));

        jbtn1.setBackground(new java.awt.Color(204, 255, 204));
        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setBorder(null);
        jbtn1.setFocusPainted(false);
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 90));

        jbtn4.setBackground(new java.awt.Color(204, 255, 204));
        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setBorder(null);
        jbtn4.setFocusPainted(false);
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 90));

        jbtn6.setBackground(new java.awt.Color(204, 255, 204));
        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setBorder(null);
        jbtn6.setFocusPainted(false);
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, 90));

        jbtn5.setBackground(new java.awt.Color(204, 255, 204));
        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setBorder(null);
        jbtn5.setFocusPainted(false);
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, 90));

        jbtn7.setBackground(new java.awt.Color(204, 255, 204));
        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setBorder(null);
        jbtn7.setFocusPainted(false);
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 90));

        jbtn8.setBackground(new java.awt.Color(204, 255, 204));
        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setBorder(null);
        jbtn8.setFocusPainted(false);
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 80, 90));

        jbtn9.setBackground(new java.awt.Color(204, 255, 204));
        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setBorder(null);
        jbtn9.setFocusPainted(false);
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 90));

        jPanel13.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 300, 470));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produse", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSprite.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/sprite.png"))); // NOI18N
        jbtnSprite.setBorder(null);
        jbtnSprite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSprite.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnSprite.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpriteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 140));

        jbtnCola.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/cola.png"))); // NOI18N
        jbtnCola.setBorder(null);
        jbtnCola.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCola.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCola.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnColaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 140));

        jbtnCafea.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCafea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/cafea.png"))); // NOI18N
        jbtnCafea.setBorder(null);
        jbtnCafea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCafea.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCafea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCafea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCafeaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCafea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 140));

        jbtnSendvis.setBackground(new java.awt.Color(255, 255, 255));
        jbtnSendvis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/sendvis.png"))); // NOI18N
        jbtnSendvis.setBorder(null);
        jbtnSendvis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSendvis.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnSendvis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSendvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSendvisActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSendvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, 140));

        jbtnFanta.setBackground(new java.awt.Color(255, 255, 255));
        jbtnFanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/fanta.png"))); // NOI18N
        jbtnFanta.setBorder(null);
        jbtnFanta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnFanta.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnFanta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFantaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 140));

        jbtnAripioarePui.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAripioarePui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/aripioare_pui.png"))); // NOI18N
        jbtnAripioarePui.setBorder(null);
        jbtnAripioarePui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnAripioarePui.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnAripioarePui.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnAripioarePui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAripioarePuiActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAripioarePui, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 120, 140));

        jbtnShaorma.setBackground(new java.awt.Color(255, 255, 255));
        jbtnShaorma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/shaorma.png"))); // NOI18N
        jbtnShaorma.setBorder(null);
        jbtnShaorma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnShaorma.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnShaorma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnShaorma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShaormaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnShaorma, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 120, 140));

        jbtnHotdog.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHotdog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/hotdog.png"))); // NOI18N
        jbtnHotdog.setBorder(null);
        jbtnHotdog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHotdog.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnHotdog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnHotdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHotdogActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 140));

        jbtnCartofiPai.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCartofiPai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/cartofi_pai.png"))); // NOI18N
        jbtnCartofiPai.setBorder(null);
        jbtnCartofiPai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCartofiPai.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCartofiPai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCartofiPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCartofiPaiActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnCartofiPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 120, 140));

        jbtnHamburgerSimplu.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHamburgerSimplu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/hamburger.png"))); // NOI18N
        jbtnHamburgerSimplu.setBorder(null);
        jbtnHamburgerSimplu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHamburgerSimplu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnHamburgerSimplu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnHamburgerSimplu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHamburgerSimpluActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHamburgerSimplu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 120, 140));

        jbtnFelie_pizza.setBackground(new java.awt.Color(255, 255, 255));
        jbtnFelie_pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/pizza.png"))); // NOI18N
        jbtnFelie_pizza.setBorder(null);
        jbtnFelie_pizza.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnFelie_pizza.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnFelie_pizza.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnFelie_pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFelie_pizzaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnFelie_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 140));

        jbtnHamburgerDublu.setBackground(new java.awt.Color(255, 255, 255));
        jbtnHamburgerDublu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/hamburger_dublu.png"))); // NOI18N
        jbtnHamburgerDublu.setBorder(null);
        jbtnHamburgerDublu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHamburgerDublu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnHamburgerDublu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnHamburgerDublu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHamburgerDubluActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnHamburgerDublu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 120, 140));

        jbtnMeniu1.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMeniu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/meniu1.png"))); // NOI18N
        jbtnMeniu1.setBorder(null);
        jbtnMeniu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMeniu1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnMeniu1.setOpaque(true);
        jbtnMeniu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnMeniu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMeniu1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnMeniu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, 140));

        jbtnMeniu2.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMeniu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/meniu2.png"))); // NOI18N
        jbtnMeniu2.setBorder(null);
        jbtnMeniu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMeniu2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnMeniu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnMeniu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMeniu2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnMeniu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, 140));

        jbtnPizzaMare.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPizzaMare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Produse/pizza_mare.png"))); // NOI18N
        jbtnPizzaMare.setActionCommand("2");
        jbtnPizzaMare.setBorder(null);
        jbtnPizzaMare.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPizzaMare.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnPizzaMare.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPizzaMare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzaMareActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPizzaMare, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 140));

        jPanel13.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 470));

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bon curent", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(51, 204, 0));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produs", "Cantitate", "Preț"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Lista produselor adăugate");
        jTable1.setAlignmentX(0.0F);
        jTable1.setAlignmentY(0.0F);
        jTable1.setGridColor(new java.awt.Color(230, 230, 230));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 440));

        jPanel13.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 360, 470));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       
       //=============================Function=================================================
       
    public void ItemCost()
    {
        double suma = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            suma =  suma + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
          
        }
        //jtxtSubTotal.setText(Integer.toString(sum));
        jtxtPret_brut.setText(Double.toString(suma));
        double cTotal1 = Double.parseDouble(jtxtPret_brut.getText());
        
        double TVA = (cTotal1 *19)/100;
        String iTaxTotal = String.format("%.2f LEI", TVA);
        jtxtTVA.setText(iTaxTotal);
        
        String iSubTotal = String.format("%.2f LEI", cTotal1);
        jtxtPret_brut.setText(iSubTotal);
        
        String iTotal = String.format("%.2f LEI", TVA + cTotal1);
        jtxtPret_Total.setText(iTotal); 
        
       
    }
//==========================================Function================================================
     public void calcul_rest()
    {        
        double suma= 0;
        double TVA =19;        
        double cash = Double.parseDouble(jtxtNumerar.getText());
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            suma =  suma + Double.parseDouble(jTable1.getValueAt(i, 2).toString());            
        }
        double TVA1 = (suma * TVA)/100; 
        double act = (cash - (suma + TVA1));      
        String actualizare = String.format(" %.2f LEI", act);
        jtxtRest.setText(actualizare);     
  
}
    
//=========================================================================== 
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String numar_introdus = jtxtNumerar.getText();   
        
               
        if (numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn1.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn1.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn2.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn2.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String numar_introdus = jtxtNumerar.getText();  
              
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn4.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn4.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String numar_introdus = jtxtNumerar.getText();           
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn5.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn5.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
         String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn6.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn6.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
         String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn7.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn7.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn8.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn8.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn9.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn9.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String numar_introdus = jtxtNumerar.getText();   
        
               
        if (numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn0.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn0.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
         if(! jtxtNumerar.getText().contains("."))
        {
        jtxtNumerar.setText(jtxtNumerar.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String numar_introdus = jtxtNumerar.getText();   
        
               
        if ( numar_introdus == "")
        {
            jtxtNumerar.setText(jbtn3.getText());
        }
        else
        {
            numar_introdus = jtxtNumerar.getText() + jbtn3.getText();
             jtxtNumerar.setText(numar_introdus);   
                }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
         jtxtNumerar.setText("");
         jtxtRest.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed
private JFrame frame;
    private void jButton_InchidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InchidereActionPerformed
        frame = new JFrame("Iesire");
        if (JOptionPane.showConfirmDialog(frame, "Doriti sa iesiti?","Confirmare inchidere aplicatie",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_InchidereActionPerformed

    private void jbtnIncaseazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIncaseazaActionPerformed
        if (jtxtMetoda_plata.getSelectedItem().equals("Numerar"))
            {
                calcul_rest();               
            }
            else
            {
                jtxtRest.setText("");
                jtxtNumerar.setText("");
            }
        
        
    }//GEN-LAST:event_jbtnIncaseazaActionPerformed

    private void jbtnAnulare_bonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnulare_bonActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        RecordTable.setRowCount(0);
         jtxtRest.setText("");
                jtxtNumerar.setText("");
                jtxtTVA.setText("");
                jtxtPret_brut.setText("");
                jtxtPret_Total.setText("");
    }//GEN-LAST:event_jbtnAnulare_bonActionPerformed

    private void jbtnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnColaActionPerformed
        double pret_produs = 3;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Doza Cola","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnColaActionPerformed

    private void jbtnCafeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCafeaActionPerformed
        double pret_produs = 3;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pahar cafea","1",pret_produs});
        
        ItemCost();
    }//GEN-LAST:event_jbtnCafeaActionPerformed

    private void jbtnHotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHotdogActionPerformed
        double pret_produs = 4;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hotdog","1",pret_produs});
        
        ItemCost();
    }//GEN-LAST:event_jbtnHotdogActionPerformed

    private void jbtnFelie_pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFelie_pizzaActionPerformed
       double pret_produs = 6;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Felie pizza","1",pret_produs});
        
        ItemCost();
    }//GEN-LAST:event_jbtnFelie_pizzaActionPerformed

    private void jbtnPizzaMareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzaMareActionPerformed
        double pret_produs = 25;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pizza mare","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnPizzaMareActionPerformed

    @SuppressWarnings("StringEquality")
    private void jbtnStergere_produsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStergere_produsActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();          
             
        int  RemoveItem =  jTable1.getSelectedRow();                      
        if (RemoveItem >= 0)
        {
        model.removeRow(RemoveItem);  
        }   
        
        ItemCost();
        
        if (jtxtMetoda_plata.getSelectedItem().equals("Numerar"))
            {
                calcul_rest();               
            }
        
        String numar_introdus = jtxtNumerar.getText();
                       
        if (numar_introdus == "" && jtxtMetoda_plata.getSelectedItem().equals("Numerar"))
        {      
            
                jtxtRest.setText("");
                jtxtNumerar.setText("");
            }
    }//GEN-LAST:event_jbtnStergere_produsActionPerformed

    private void jbtnFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFantaActionPerformed
        double pret_produs = 3;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Fanta","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnFantaActionPerformed

    private void jbtnSendvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSendvisActionPerformed
      double pret_produs = 6.3;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Senvis","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnSendvisActionPerformed

    private void jbtnShaormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShaormaActionPerformed
        double pret_produs = 8;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Shaorma","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnShaormaActionPerformed

    private void jbtnHamburgerSimpluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHamburgerSimpluActionPerformed
         double pret_produs = 8.5;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hamburger Simplu","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnHamburgerSimpluActionPerformed

    private void jbtnHamburgerDubluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHamburgerDubluActionPerformed
       double pret_produs = 10;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hamburger Dublu","1",pret_produs});        
        ItemCost(); 
    }//GEN-LAST:event_jbtnHamburgerDubluActionPerformed

    private void jbtnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpriteActionPerformed
        double pret_produs = 3;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sprite","1",pret_produs});        
        ItemCost(); 
    }//GEN-LAST:event_jbtnSpriteActionPerformed

    private void jbtnCartofiPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCartofiPaiActionPerformed
         double pret_produs = 4;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cartofi pai","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnCartofiPaiActionPerformed

    private void jbtnAripioarePuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAripioarePuiActionPerformed
        double pret_produs = 9;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Aripioare pui","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnAripioarePuiActionPerformed

    private void jbtnMeniu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMeniu2ActionPerformed
        double pret_produs = 17.5;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Salata de pui","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnMeniu2ActionPerformed

    private void jbtnMeniu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMeniu1ActionPerformed
        double pret_produs = 15;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Meniu Hamburger","1",pret_produs});        
        ItemCost();
    }//GEN-LAST:event_jbtnMeniu1ActionPerformed

    private void jbtnEmite_bonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmite_bonActionPerformed
         MessageFormat header = new MessageFormat("Factura fiscala Nr.1!");
         MessageFormat footer = new MessageFormat("Pagina {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Nu a fost gasita nicio imprimanta!", e.getMessage());
        }
    }//GEN-LAST:event_jbtnEmite_bonActionPerformed

    private void jtxtTVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTVAActionPerformed

    private void jtxtMetoda_plataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMetoda_plataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMetoda_plataActionPerformed

    private void jtxtPayMethod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPayMethod1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPayMethod1ActionPerformed

    private void jtxtPayMethod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPayMethod2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPayMethod2ActionPerformed

    private void jtxtPayMethod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPayMethod3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPayMethod3ActionPerformed

    private void jtxtPret_brutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPret_brutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPret_brutActionPerformed

    private void jtxtNumerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Inchidere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAnulare_bon;
    private javax.swing.JButton jbtnAripioarePui;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCafea;
    private javax.swing.JButton jbtnCartofiPai;
    private javax.swing.JButton jbtnCola;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnEmite_bon;
    private javax.swing.JButton jbtnFanta;
    private javax.swing.JButton jbtnFelie_pizza;
    private javax.swing.JButton jbtnHamburgerDublu;
    private javax.swing.JButton jbtnHamburgerSimplu;
    private javax.swing.JButton jbtnHotdog;
    private javax.swing.JButton jbtnIncaseaza;
    private javax.swing.JButton jbtnMeniu1;
    private javax.swing.JButton jbtnMeniu2;
    private javax.swing.JButton jbtnPizzaMare;
    private javax.swing.JButton jbtnSendvis;
    private javax.swing.JButton jbtnShaorma;
    private javax.swing.JButton jbtnSprite;
    private javax.swing.JButton jbtnStergere_produs;
    private javax.swing.JComboBox<String> jtxtMetoda_plata;
    private javax.swing.JTextField jtxtNumerar;
    private javax.swing.JTextField jtxtPret_Total;
    private javax.swing.JTextField jtxtPret_brut;
    private javax.swing.JTextField jtxtRest;
    private javax.swing.JTextField jtxtTVA;
    // End of variables declaration//GEN-END:variables
}
